/*
 * INSERT INTO customer
*/

INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Amelie', 'O''Reilly', '7358 Ziemann Track', 'Zechariahhaven', '16895', 'Willow.Waters47@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Erika', 'O''Kon', '45371 Jolie Ways', 'Madelineville', '49007-0173', 'Yvonne.Witting@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Mittie', 'Batz', '2591 Kuphal Branch', 'Elisabethchester', '68919-9729', 'Kenya.Bogan@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nannie', 'Koelpin', '25655 Beryl Parkways', 'Schowalterville', '63142', 'Monique.Mitchell@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Oda', 'Sawayn', '38316 Mike Common', 'Lake Alek', '00490', 'Berneice_Barrows28@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Vesta', 'Toy', '138 Kadin Pine', 'New Emmanuelchester', '34125-4488', 'Lucinda.Strosin@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Moriah', 'Paucek', '958 Gerlach Freeway', 'Boscoville', '86172-0239', 'Karen.Jacobi14@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Sibyl', 'Kessler', '206 Jessica Rest', 'North Emma', '51989', 'Amelia.Kessler@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Chaim', 'Kovacek', '6296 Borer Mountain', 'Angelobury', '43170-1311', 'Kyler_Kerluke@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Luisa', 'Sipes', '7611 Eleonore Loaf', 'East Rowland', '77863', 'Loren_Wolf@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Clovis', 'Schmitt', '0706 Tromp Mount', 'South Maximillianshire', '14893', 'Dexter70@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('August', 'Zemlak', '06199 Manley Parkway', 'West Katrineshire', '63771-4593', 'Cyrus94@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Darrick', 'Nitzsche', '25309 Lucie Green', 'North Kayden', '25910', 'Dina.Hickle@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Therese', 'Krajcik', '43610 Aletha Plaza', 'Harberborough', '87028', 'Cleveland69@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Deja', 'Rutherford', '5954 Harris Mall', 'Port Elvis', '32413', 'Laurel.Howell20@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Johnson', 'Pfeffer', '406 Hyatt Cliff', 'Weberville', '44817', 'Coralie29@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Delaney', 'Kuhlman', '818 Larson Circle', 'West Royalmouth', '97830', 'Hal.Brown12@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Piper', 'Windler', '956 Alyce Parks', 'Lake Andymouth', '05626', 'Rod.Herzog56@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jarrett', 'Sanford', '5250 Vidal Island', 'New Dorcas', '95741', 'Kaci.Schneider@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Crystel', 'Homenick', '75151 Ebert Manor', 'West Xander', '67717', 'Jayden43@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bridget', 'Quigley', '329 Minnie Village', 'Ernestinaton', '52333', 'Maddison.Lind95@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Isidro', 'Hansen', '763 Leila Greens', 'Port Toney', '23376', 'Ava45@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Keira', 'Hintz', '459 Raynor Loaf', 'Nigelberg', '43591', 'Lavina.Witting@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elvera', 'Oberbrunner', '842 Quitzon Stream', 'East Drake', '78165', 'Carli46@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rocky', 'Metz', '209 Rowe Burg', 'Port Michaela', '86586', 'Lukas.Conroy@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rhiannon', 'Cartwright', '0482 Yvette Streets', 'New Amiya', '22253', 'Emerald77@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Shany', 'Keeling', '001 Mohammad Run', 'New Nicholaston', '33009-1504', 'Duane_Lesch@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lauren', 'Larkin', '681 Marvin Motorway', 'Port Thomasview', '49710-2903', 'Kris_Kiehn26@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Pearl', 'Lakin', '9572 Kayden Trace', 'Hudsonfort', '11073', 'Lionel.Fadel@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Erick', 'Welch', '9127 Hammes Drive', 'South Delfinaburgh', '49770', 'Leif_Smitham@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Oceane', 'Herman', '112 Wiza Rapids', 'New Cristina', '02729', 'Mark47@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Theresia', 'Wisozk', '07225 Yundt Lakes', 'Lake Elena', '42169', 'Vivian35@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kaitlin', 'VonRueden', '921 Beahan Station', 'Natashafurt', '66974-6287', 'Claudie_Moen53@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jazmyne', 'Kerluke', '987 Melisa Junction', 'Orvalchester', '34752-6648', 'Cayla_Jacobs83@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Larry', 'Hegmann', '8805 Hans Vista', 'Alvaville', '25565-4938', 'Aron.Crooks@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Al', 'Nitzsche', '43705 Avery Extension', 'East Chestertown', '21089', 'Valentina_Kozey@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elian', 'Morar', '125 Tate Club', 'Elinorestad', '55136-9300', 'Bartholome53@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ulises', 'Sipes', '50702 Zechariah Cove', 'West Eleanoreshire', '82673', 'Jacklyn0@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kaylah', 'Satterfield', '407 Kemmer Ridges', 'East Elmiratown', '51484', 'Nathanael.Wintheiser@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dwight', 'Wilderman', '6026 McDermott Landing', 'Welchshire', '65834', 'Camron_Haley33@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Brody', 'Doyle', '118 Domenic View', 'West Tiannaland', '31955-0892', 'Jeramy.Murphy@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cornell', 'Hoppe', '863 Mavis Walks', 'Geovannitown', '69868-1705', 'Brady11@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nigel', 'Hessel', '7116 Isabella Terrace', 'Hackettstad', '05297-5211', 'Zakary.Larson78@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jennie', 'Schowalter', '763 Adrienne Light', 'Llewellynberg', '18595', 'Carolina_Klein89@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jamal', 'Kris', '712 Zack Falls', 'Adaland', '34137-1753', 'Enrique.Marquardt@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gust', 'Robel', '89665 Ignacio Forge', 'Jamaalside', '56804', 'Mable.Lesch@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Otilia', 'Maggio', '90642 Peter Cliff', 'New Rosemariemouth', '17047', 'Diamond17@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Leila', 'Walker', '234 Mariela Trail', 'Cormierview', '23653', 'Lesly.Cole55@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gay', 'Lebsack', '5416 Kling Ramp', 'Margetown', '26463', 'Rick.DAmore2@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Maye', 'Rempel', '777 Kunze Cliffs', 'East Coltenburgh', '65627-9264', 'Ali.Lueilwitz63@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Willow', 'Murazik', '222 Marianna Stravenue', 'Lake Adrienne', '23676-7817', 'Brian_Murazik7@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elda', 'Kuhn', '2709 Coty Heights', 'Elliotttown', '37505', 'Velma.Ullrich87@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lelah', 'Abshire', '5774 D''angelo Crescent', 'West Natashafurt', '52518-9342', 'Lorenzo_Vandervort31@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Melba', 'White', '709 Herman Cliff', 'Gladysborough', '78159', 'Spencer.Cartwright@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nikolas', 'Hoeger', '1240 Terrence Crest', 'Hegmannland', '22586', 'Bethany_Batz@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Easton', 'Paucek', '911 Ruecker Overpass', 'Lake Emmaleefort', '69889-9834', 'Florencio.Doyle98@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Carmella', 'Raynor', '951 Schowalter Extensions', 'New Gaetanobury', '29901-1914', 'Cheyenne30@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Joe', 'Harber', '95583 Pete Hill', 'West Abigayleville', '00757', 'Caitlyn19@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rico', 'Ullrich', '5944 Antone Loaf', 'Port Mertie', '79150-9911', 'Imani72@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bonnie', 'Ryan', '746 Raynor Inlet', 'Brakuston', '34328-3169', 'Rosemary69@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Josiane', 'Rau', '30513 Beahan Lodge', 'East Rodolfoshire', '09242', 'Katrina38@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ben', 'Jerde', '37565 Huel Common', 'Brakusburgh', '46677-5084', 'Dixie.Mosciski84@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kelly', 'Corkery', '1436 Daniel Cliff', 'East Terrellview', '44830-1502', 'Estefania_Upton24@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Brielle', 'DuBuque', '3271 Jacynthe Shoals', 'West Alanna', '54815-3139', 'Maybell_Anderson@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Boyd', 'White', '00796 Ernser Ridges', 'Fredrickshire', '63363', 'Rachael.Blick65@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Noel', 'Bruen', '991 Ebert Station', 'Myrlstad', '27927', 'Ewald89@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Santino', 'Jenkins', '418 Kacie Island', 'Eltonshire', '64101', 'Afton.Hickle96@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dashawn', 'Kulas', '6364 Trantow Mission', 'Cummingstown', '37842', 'Sheila94@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jannie', 'Volkman', '5069 McKenzie Square', 'New Danikaside', '20319-3422', 'Anya30@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Tomasa', 'Stamm', '651 Dillan Cliffs', 'Gunnerland', '24602', 'Meda_Towne@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Myrna', 'Hyatt', '96147 Bradtke Ville', 'Lake Ellis', '58061', 'Rey5@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Murray', 'Weissnat', '581 Gusikowski Crescent', 'North Imani', '03697', 'Geo31@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Josephine', 'West', '6879 Stark Springs', 'Lake Delfinafort', '33900-9601', 'Jackson_Maggio@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Keshawn', 'Bogisich', '78017 Dickinson Curve', 'Dominiquebury', '44698-7814', 'Athena.Funk@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Titus', 'Sawayn', '5229 Asa Spur', 'South Alaynaburgh', '37923-5403', 'Gunner_Jerde@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Constance', 'Rice', '7442 Crist Harbors', 'Grantmouth', '23265', 'Mossie_Willms@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lucie', 'Toy', '379 Edward Cliffs', 'Mitchelltown', '52777', 'Keyshawn_Heidenreich@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kristina', 'Schiller', '3342 Conner Isle', 'Hopeside', '79934', 'Christine82@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gregorio', 'Botsford', '65174 Faustino Spring', 'North Salma', '90881', 'Eunice.Cole25@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lou', 'Crooks', '7598 Lind Extension', 'New Helenaburgh', '23563-7301', 'Neil_Howe@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bulah', 'Kohler', '029 Schuster Plains', 'Spencerborough', '49254-6989', 'Woodrow_Graham64@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Reagan', 'O''Conner', '32223 Ally Mill', 'Langhaven', '72670', 'Dewitt_Schamberger@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elfrieda', 'O''Keefe', '2592 Cheyanne Stream', 'East Royal', '13962', 'Heath.Upton78@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rosetta', 'Wisoky', '86896 Legros Ridges', 'Cummingshaven', '76694', 'Jeramie_Barton4@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lola', 'McKenzie', '50991 Mose Turnpike', 'Ernserberg', '05725-4607', 'Jeanne.OConner@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Shyanne', 'Batz', '8857 Johathan Hill', 'Hankmouth', '04113', 'Elva35@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nathen', 'Schowalter', '67061 Stracke Street', 'Othamouth', '25399', 'Domenico_Cole@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ruth', 'Grant', '06583 Sadye Overpass', 'Hildaborough', '41409-7452', 'Laury22@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Arnold', 'Friesen', '4520 Upton Parkways', 'Huelborough', '40530-3029', 'Percival.Keeling13@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Corine', 'Dicki', '1163 Damien Expressway', 'Port Jaronhaven', '83463-8521', 'Hertha83@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Selmer', 'Conn', '4096 Wiegand Field', 'Wolfborough', '19088', 'Christelle39@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dina', 'Lowe', '204 Effie Causeway', 'North Murray', '15020-4031', 'Arthur7@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elsie', 'Bayer', '868 Feest Field', 'South Alvena', '35174', 'Otilia.Schultz@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Treva', 'Nicolas', '178 Leffler Coves', 'Lilianeport', '93486', 'Arden_Cartwright42@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cindy', 'Littel', '01001 Kreiger Loaf', 'North Marisol', '13517-6963', 'Gudrun.McLaughlin@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Frankie', 'Kunze', '5057 Stroman Club', 'West Kiera', '43498-9060', 'Harrison.Barton15@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Robin', 'Schaefer', '46423 Bahringer Hollow', 'East Vivienne', '34676', 'Justice_Jacobi63@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Morris', 'Kiehn', '9346 Haag Summit', 'Kautzerchester', '62696-0240', 'Horacio_Leannon88@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Carissa', 'Satterfield', '98934 Trevor Coves', 'Lednerborough', '26583', 'Marielle_Feil18@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Hobart', 'Klocko', '0716 Nathen Hollow', 'Ursulaside', '38449-2967', 'Valentine10@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Amie', 'Satterfield', '9649 Deborah Crest', 'Dedrickland', '30691', 'Xzavier_Gleichner@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ilene', 'Graham', '927 Terence Tunnel', 'South Maynard', '33621', 'Stanton83@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kailyn', 'Ferry', '37796 Josiane Lodge', 'East Michealchester', '30620-6443', 'Eriberto_Heaney45@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Carli', 'Greenholt', '5946 Vito Keys', 'Pfannerstillhaven', '27029', 'Pierre19@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Blanche', 'Kozey', '5071 Destiny Summit', 'North Elouisebury', '08717-6587', 'Linda_Parker13@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Alba', 'Hamill', '132 Daisha Tunnel', 'Nicklausville', '20174', 'Luis38@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Whitney', 'Davis', '8860 Faye Ridges', 'Thompsonberg', '42122', 'Gianni_Smith78@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Laurine', 'Koepp', '866 Frederik Plain', 'New Fatima', '71418', 'Genoveva55@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kellen', 'Jacobs', '907 Elda Tunnel', 'Port Eino', '49512', 'Rudolph36@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kole', 'Wilkinson', '094 Reinger Pines', 'New Andreaneville', '14775-3358', 'Ron98@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Aurelio', 'Blanda', '7576 Murphy Harbors', 'Amandaport', '91968', 'Fatima_Boyle87@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Hermann', 'Reynolds', '23482 White Place', 'Lake August', '47065', 'Noelia.Mayert41@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Reagan', 'Hintz', '4099 Effertz Meadow', 'Ortizbury', '34301', 'Vida67@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dedric', 'Johnston', '8597 Brice Ridges', 'Schillerside', '96392-1453', 'Stanley44@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Asha', 'Brown', '53587 Joyce Plaza', 'New Dahliaburgh', '29822-9597', 'Elenora_Barrows5@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Eugenia', 'Bailey', '044 Terry Keys', 'Lake Flavioberg', '92469', 'Kaci_Balistreri@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bennie', 'Wiegand', '03644 Susana Court', 'Lake Arielleton', '45944', 'Alexis_Klein36@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Retta', 'Jones', '548 Halvorson Forest', 'Beattyton', '02565', 'Gaston_Carroll@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Zachariah', 'Metz', '894 Mann Village', 'Watsicashire', '99907', 'Robb.Gusikowski@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Leslie', 'Willms', '7863 Satterfield Corners', 'South Maegan', '49071-7701', 'Loren_Swaniawski@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jewell', 'Towne', '2822 Ian Falls', 'North Jimmy', '86025-4830', 'Georgianna.Von15@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Grayce', 'Olson', '9438 Sunny Wells', 'Fionashire', '73391-8320', 'Deontae74@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rachel', 'Ebert', '13293 Robbie Field', 'North Unaburgh', '49817-2692', 'Karen.Wunsch10@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Raphaelle', 'Shields', '0620 Jackie Inlet', 'Elimouth', '71729', 'Jack1@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Syble', 'Cummerata', '3069 Roob Locks', 'Trompfurt', '26550-3690', 'Chance.Bahringer96@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Arne', 'Jakubowski', '32241 Summer Forest', 'West Makennafort', '91431-3019', 'Olen.Dibbert@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Amiya', 'Littel', '4009 White Common', 'New Tracyberg', '04096', 'Emory.Ondricka99@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Constance', 'Wilkinson', '52575 Summer Bypass', 'Forrestshire', '34761-8905', 'Shad.Nolan31@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Loraine', 'Quigley', '059 Brown Islands', 'Huelville', '90821', 'Kiana86@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rosalyn', 'Homenick', '602 Garnet Stream', 'Starktown', '72475-7481', 'Gennaro.Luettgen66@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Marques', 'Tremblay', '8110 Aurelio Port', 'West Lavon', '90244-4977', 'Aurelio70@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Titus', 'Ritchie', '1328 Genoveva Lodge', 'West Ronny', '27212', 'George.Morissette@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cyrus', 'Stoltenberg', '2898 Klein Alley', 'West Leopoldo', '03937', 'Ivy_Hickle79@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Stewart', 'Heidenreich', '062 Kale Station', 'East Zoie', '61018-0469', 'Chance.Mueller@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Emmie', 'Schuppe', '2189 Predovic Lake', 'Murazikberg', '56161', 'Murray_Wolf@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Devyn', 'Heller', '32992 Horacio Forest', 'Pacochaland', '19963-3407', 'Jackeline10@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Stanley', 'Jacobson', '653 Legros Station', 'Lake Maureenport', '73109-7100', 'Moriah1@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gracie', 'Nader', '8506 Lakin Shores', 'Vivienborough', '77707-7859', 'Darryl.Hoppe66@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lew', 'Willms', '0582 O''Kon Track', 'Port Brannonport', '32065', 'Iva.Zulauf45@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gerda', 'Hickle', '1504 Zita Divide', 'North Reta', '30145', 'Kenyatta_Keebler@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Abbey', 'Krajcik', '270 Henri Ville', 'Parisianburgh', '48127-5871', 'Jairo_Green15@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Mandy', 'Kiehn', '7305 Ernesto Drive', 'McGlynnberg', '43014', 'Humberto72@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Andreanne', 'Nolan', '360 Bailey Branch', 'East Rustytown', '84749-4338', 'Wilmer.Schroeder@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jo', 'Bosco', '266 Gottlieb Gateway', 'East Thomas', '05348-4908', 'Jude.Gerlach@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Deborah', 'Jakubowski', '3449 Ellsworth Lane', 'New Fausto', '21280-7913', 'Jose.Stracke21@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Daisha', 'Kovacek', '8923 West Manor', 'Hilllborough', '86121', 'Watson.Tillman66@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Barbara', 'Wisoky', '647 Trantow Rest', 'Lake Estebanbury', '50086-7746', 'Jodie11@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Desmond', 'Russel', '7925 Spencer Meadows', 'Sidneyland', '42959-1685', 'Sim_Koch@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Devonte', 'Schowalter', '529 Vance Knoll', 'Alisonshire', '35915-5337', 'Aurelio.Kovacek19@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Raegan', 'Wisoky', '84571 Davis Vista', 'Port Paigeport', '23062', 'Sylvester_Farrell@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rosetta', 'Hauck', '0009 Gerhold Mountain', 'South Martinton', '12302', 'Muhammad_Maggio@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Iliana', 'Goyette', '91334 Tressa Wall', 'East Haydenview', '97718-0223', 'Kristina.Conn@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Orval', 'Doyle', '281 Spencer Ports', 'Bradleyshire', '83424', 'Valerie_McGlynn14@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Carson', 'Wiza', '5279 Bret Street', 'West Naomiville', '56482', 'Meggie_Glover96@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jevon', 'Smitham', '1113 Norene Roads', 'Kayliland', '08300-4567', 'Karli.Fritsch36@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jayne', 'Nikolaus', '271 Karli Island', 'South Chaz', '71750-9284', 'Wilhelmine_Kassulke@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kim', 'Jones', '428 Marlen Ranch', 'East Wilbert', '70078', 'Vinnie_Gleichner87@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Abdul', 'Hartmann', '59607 Berneice Expressway', 'Lauriemouth', '68204', 'Kiarra93@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Clint', 'Kessler', '3052 Santina Brooks', 'Brantview', '39638', 'Berry10@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dane', 'Hackett', '1095 Lueilwitz Prairie', 'Kemmerstad', '72641-7795', 'Vicenta64@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Alexane', 'Labadie', '65750 Savanna Causeway', 'Thoraburgh', '43011', 'Kenyatta6@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elmira', 'Schinner', '97192 Lubowitz Vista', 'Port Clementchester', '80854-3176', 'Keshawn_OConnell@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elda', 'Rempel', '4526 Toy Inlet', 'Lonnieview', '89930-2342', 'Rhea.Schultz13@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Fabian', 'Kling', '7054 Loy Brook', 'New Elwyn', '93429-4246', 'Spencer_Willms@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Matilda', 'Batz', '647 Dolly Stravenue', 'East Jack', '82339', 'Noah_Cruickshank43@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Maynard', 'Haley', '6912 Cecil Valley', 'Solonville', '31306', 'Abdiel_Rippin84@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Osborne', 'Raynor', '0671 Albert Forks', 'West Aliyafurt', '79773', 'Elise.Dietrich71@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Litzy', 'Jakubowski', '8469 Oma Extensions', 'Boganport', '05783', 'Ross.Reichert29@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Johanna', 'Cronin', '7074 Tillman Locks', 'Port Lloydland', '27406-9061', 'Gordon_Marvin66@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Hermann', 'Hilll', '56132 Dixie River', 'Haleyview', '32190', 'Bart9@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Zechariah', 'Jacobi', '22143 Christian Ranch', 'East Ronny', '55756-4659', 'Avery_Borer10@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Deja', 'Ankunding', '54204 Schmeler Flat', 'Port Jeromy', '37215', 'Selena_Rosenbaum86@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Alene', 'Murazik', '891 Janie Roads', 'East Mateo', '37272-6088', 'Gabe.Halvorson89@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dax', 'Heathcote', '5641 Wiza Spur', 'Lucienneview', '27224', 'Della69@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Keely', 'Kulas', '941 Isac Bridge', 'New Angie', '24219-8271', 'Myra74@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Eldridge', 'Wiegand', '27091 Shakira Row', 'Osinskihaven', '38638-5612', 'Earlene.Doyle16@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Collin', 'Reinger', '1036 Bill Shoal', 'Furmanburgh', '74071-2723', 'Cassie_Farrell@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Maxime', 'Abernathy', '32330 Ferry Prairie', 'Veumborough', '55143', 'Orion_Swift96@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Daphney', 'Corkery', '944 Keven Forges', 'New Collin', '83618-6041', 'Reinhold.Feil@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Karelle', 'Lang', '198 D''Amore Meadows', 'East Ava', '52383', 'Leonie_Ruecker67@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Toby', 'VonRueden', '67050 Skiles Shore', 'Balistreriside', '88331-1629', 'Alexane_Kreiger19@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Wyman', 'Wolf', '828 Dayana Lakes', 'East Dorian', '43415', 'Cleveland_Gerhold@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ryan', 'Schimmel', '659 Bella Skyway', 'Lake Helmerside', '54849', 'Eloy_Denesik@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rosie', 'Weber', '89993 Shyanne Locks', 'McCulloughtown', '91334-8812', 'Arvid92@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ethyl', 'O''Keefe', '926 Vaughn Rest', 'Lake Maximo', '73656', 'Domenica_Von@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Amani', 'Luettgen', '68111 Christiansen Lakes', 'New Emmittbury', '62176-3094', 'Carleton_Rutherford9@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Preston', 'Nicolas', '03218 Feeney Via', 'East Bufordville', '45101', 'Vidal_Doyle@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Beatrice', 'Shields', '72457 Carmel Parkway', 'Willstad', '72786', 'Emerson50@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Quinten', 'Blick', '6205 Kulas Spring', 'North Bartholome', '62092', 'Annette.Crist5@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kara', 'Monahan', '43382 Ward Wells', 'North Hermann', '38357', 'Felipa.Flatley@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Arvilla', 'Welch', '784 Quinn Dale', 'Ziemefurt', '51513-0975', 'Libby.Toy2@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Abe', 'Feeney', '833 Peter Overpass', 'Lylaside', '81736', 'Eric.Waters75@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cheyanne', 'Green', '62003 Grant Orchard', 'Clemmiemouth', '02787', 'Anahi13@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Eduardo', 'McKenzie', '3161 Cremin Street', 'Lebsackview', '66494-5553', 'Elijah.Smith@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Roel', 'Braun', '7733 Beatty Expressway', 'Huelfurt', '09666-5002', 'Pierce.Larkin4@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cali', 'Gulgowski', '94119 Greenfelder Greens', 'Concepcionburgh', '69096', 'Elenora_Wisoky25@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Monty', 'Goodwin', '683 Aubree Flat', 'Lauryside', '16466-5997', 'Dalton_Gusikowski33@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Myrtice', 'Schmitt', '267 Sawayn Springs', 'Lake River', '44360', 'Lia_Crist22@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Foster', 'Yundt', '715 Funk Springs', 'Lake Jacinto', '31110', 'Justyn_Mayert73@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Sylvan', 'Feil', '01255 Quigley Ridge', 'West Vadafurt', '95888', 'Richard_Romaguera90@gmail.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Keely', 'Shoosmith', 'Room 1390', 'Kota Kinabalu', '4', 'kshoosmith0@merriam-webster.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Nessy', 'Freeman', 'Suite 81', 'La Virgen', '281', 'nfreeman1@ehow.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Rabi', 'Ebdin', 'Suite 73', 'Serednye Vodyane', '9', 'rebdin2@etsy.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ira', 'Battle', '20th Floor', 'Lac du Bonnet', '0928', 'ibattle3@reddit.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Justinn', 'Maxwell', 'Room 1785', 'Gufeng', '855', 'jmaxwell4@feedburner.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Elsinore', 'Beel', 'PO Box 37363', 'Handan', '32344', 'ebeel5@guardian.co.uk');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Reynard', 'Segeswoeth', 'Apt 1661', 'Al Qaryatayn', '5', 'rsegeswoeth6@uiuc.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Sheilah', 'Parmeter', 'Suite 100', 'Pictou', '52', 'sparmeter7@myspace.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Lewes', 'Trembley', 'Suite 46', 'Géfyra', '9241', 'ltrembley8@wisc.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Gilda', 'Jerdon', 'Room 133', 'Koua', '52581', 'gjerdon9@edublogs.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kimmi', 'Croker', 'Suite 86', 'Hanting', '085', 'kcrokera@storify.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Emlen', 'Kynaston', 'PO Box 12453', 'Moulay Abdallah', '08523', 'ekynastonb@sohu.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Robert', 'Jerdan', 'Room 524', 'Budva', '8', 'rjerdanc@scientificamerican.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Bern', 'Dashwood', 'Room 1637', 'Hongping', '5305', 'bdashwoodd@so-net.ne.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Sheelagh', 'Fleis', 'Suite 70', 'Antioquia', '9', 'sfleise@flickr.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Noll', 'Makey', 'Room 1366', 'Nesebar', '396', 'nmakeyf@aol.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Nani', 'Brunsdon', 'PO Box 3642', 'Kalipucang', '08', 'nbrunsdong@springer.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Alejandro', 'Gaine', 'Apt 1073', 'Qingxi', '35511', 'againeh@slate.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Mada', 'Dat', '20th Floor', 'Longhua', '3829', 'mdati@tumblr.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Anthia', 'Sneezum', 'Room 642', 'Muara Siberut', '5797', 'asneezumj@slashdot.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kristine', 'Montgomery', '15th Floor', 'Lagoa', '443', 'kmontgomeryk@kickstarter.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Chucho', 'Hurburt', 'Suite 62', 'Dongxin', '09531', 'churburtl@irs.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Fax', 'Attril', 'Apt 1946', 'Futtsu', '130', 'fattrilm@sogou.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Sarajane', 'Fermin', 'Apt 166', 'Omiš', '1263', 'sferminn@berkeley.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Alida', 'Grosier', 'Suite 36', 'Daluo', '212', 'agrosiero@tuttocitta.it');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Jaquith', 'Celez', 'Apt 1323', 'Novoye Devyatkino', '84', 'jcelezp@toplist.cz');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Gaelan', 'Rice', '3rd Floor', 'Ålesund', '2762', 'griceq@nasa.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Delmar', 'Elvidge', 'Apt 186', 'Taiping', '48', 'delvidger@sbwire.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Conroy', 'Crews', '16th Floor', 'Río Guayabal de Yateras', '101', 'ccrewss@spotify.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Denny', 'Calbaithe', 'Suite 81', 'Saint Helier', '48580', 'dcalbaithet@dropbox.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Rosabel', 'Espadate', 'Room 1725', 'Nan’ao', '12422', 'respadateu@nyu.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Seline', 'Warlton', 'Apt 744', 'Hulitu', '3', 'swarltonv@boston.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Connor', 'Battle', 'Room 29', 'Minato', '534', 'cbattlew@house.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Cami', 'Dowtry', 'PO Box 58385', 'Banjar Pande', '25', 'cdowtryx@zdnet.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Vinson', 'Thal', 'Apt 1310', 'Lago dos Rodrigues', '47021', 'vthaly@reddit.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Sascha', 'Jewess', 'Suite 81', 'Fatumnasi', '28', 'sjewessz@tumblr.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Isac', 'Gyer', 'PO Box 19449', 'Bohorodchany', '4', 'igyer10@jalbum.net');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Hurleigh', 'Chantillon', 'Room 1509', 'Mumias', '9337', 'hchantillon11@mlb.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dulce', 'Scannell', 'Room 1419', 'Suay', '875', 'dscannell12@hhs.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Thia', 'McAlpin', 'Room 1948', 'Sing Buri', '1', 'tmcalpin13@ameblo.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Reggis', 'Leyre', 'PO Box 92766', 'Rebe', '564', 'rleyre14@loc.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Rickey', 'Humbie', 'PO Box 90518', 'Cabouco', '7', 'rhumbie15@google.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ferdie', 'Valentin', 'Apt 1459', 'Noginsk', '4', 'fvalentin16@xing.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Yvonne', 'Feldstern', 'Suite 31', 'Beloyarskiy', '85', 'yfeldstern17@vkontakte.ru');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Brig', 'Bridgwood', 'Room 506', 'La Clotilde', '61', 'bbridgwood18@icq.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Booth', 'Guess', '13th Floor', 'Yucheng', '7', 'bguess19@zdnet.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Georgie', 'Cunningham', 'PO Box 99646', 'Ndewel', '5692', 'gcunningham1a@ycombinator.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Noby', 'Northridge', '18th Floor', 'Kamieniec Wrocławski', '89044', 'nnorthridge1b@biglobe.ne.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Augustina', 'Recher', '19th Floor', 'Zherdevka', '0', 'arecher1c@vistaprint.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kathryn', 'Jaime', 'PO Box 83629', 'Koszyce Wielkie', '109', 'kjaime1d@lycos.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Shalne', 'Thoresbie', '9th Floor', 'Madingou', '9087', 'sthoresbie1e@photobucket.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dale', 'Kemell', 'Room 1922', 'Belsk Duży', '2', 'dkemell1f@addtoany.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Horacio', 'Adamson', 'PO Box 10445', 'Buena Vista', '663', 'hadamson1g@dropbox.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Filide', 'Sexcey', 'PO Box 1947', 'Sankoutang', '3227', 'fsexcey1h@narod.ru');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Paulina', 'Menier', 'Apt 960', 'Sogcho', '9', 'pmenier1i@epa.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kipp', 'Pittle', 'Suite 56', 'Yehud', '37', 'kpittle1j@ocn.ne.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Alix', 'Lissandri', '14th Floor', 'Hamburg', '1', 'alissandri1k@mysql.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Carlita', 'Menguy', 'Suite 48', 'Myanaung', '996', 'cmenguy1l@google.com.hk');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dionis', 'Nairn', 'Room 1725', 'Partido', '45026', 'dnairn1m@google.cn');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Wynn', 'deKnevet', '17th Floor', 'Binlod', '4774', 'wdeknevet1n@unicef.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Hazlett', 'Skain', 'Suite 97', 'Araçuaí', '059', 'hskain1o@ning.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kahlil', 'Abrahmer', '4th Floor', 'Prabuty', '2', 'kabrahmer1p@shinystat.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ezekiel', 'Codi', 'Apt 462', 'Baiyashi', '04', 'ecodi1q@odnoklassniki.ru');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Adella', 'Girodier', 'Suite 14', 'Fonteleite', '7213', 'agirodier1r@senate.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Yardley', 'MacAvaddy', '7th Floor', 'Fussa', '72017', 'ymacavaddy1s@parallels.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Guillaume', 'Kain', 'Suite 56', 'San Luis', '09202', 'gkain1t@people.com.cn');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Chandler', 'Albone', 'PO Box 94140', 'Entre Rios', '1642', 'calbone1u@cornell.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Bernete', 'Madden', 'Suite 25', 'Zákynthos', '1944', 'bmadden1v@oakley.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dianne', 'Baggelley', 'Apt 993', 'Bandundu', '86', 'dbaggelley1w@trellian.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Calv', 'Muckley', 'Apt 1071', 'Sanjō', '34798', 'cmuckley1x@blogs.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Addie', 'Pulster', '2nd Floor', 'Heshi', '3', 'apulster1y@usgs.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Libbie', 'Holleworth', 'Room 56', 'Jajarkrajan', '7420', 'lholleworth1z@howstuffworks.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Flora', 'Merwe', '3rd Floor', 'Saint-Laurent-Blangy', '1825', 'fmerwe20@linkedin.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Auroora', 'Sarginson', 'Apt 1628', 'Tianyi', '669', 'asarginson21@chicagotribune.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Elliot', 'Stieger', 'PO Box 13819', 'Boleiros', '2691', 'estieger22@usnews.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Elton', 'Gallager', 'Room 578', 'Cikawunggading', '297', 'egallager23@cnbc.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Cammi', 'Faldoe', 'PO Box 24510', 'Ban Khlong Bang Sao Thong', '13385', 'cfaldoe24@loc.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Yehudi', 'Scanlon', 'Room 1719', 'Balibago', '25861', 'yscanlon25@github.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Goraud', 'Cutill', '20th Floor', 'Jönköping', '042', 'gcutill26@forbes.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Zelda', 'Riep', 'Room 1127', 'Vilares', '58143', 'zriep27@illinois.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ebeneser', 'Rasor', '20th Floor', 'Carhuac', '8', 'erasor28@baidu.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('May', 'Dodimead', 'Suite 21', 'Jaunpils', '902', 'mdodimead29@elpais.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Duke', 'Thurske', '4th Floor', 'Zalaegerszeg', '23065', 'dthurske2a@illinois.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Homer', 'Catlette', 'Apt 1359', 'Xindeng', '313', 'hcatlette2b@dailymail.co.uk');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ernestine', 'Donaher', 'Suite 94', 'Shimokizukuri', '7', 'edonaher2c@delicious.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Corly', 'Nibley', 'Apt 1433', 'Dihtyari', '0', 'cnibley2d@slideshare.net');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Jerrylee', 'Lettsom', 'Apt 1505', 'Łanięta', '27782', 'jlettsom2e@house.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Bernard', 'McEnhill', '15th Floor', 'Betaf', '847', 'bmcenhill2f@apache.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Vail', 'Harriss', 'Suite 58', 'Arinos', '065', 'vharriss2g@springer.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Blondy', 'Lattimer', 'Apt 1724', 'Pancoran', '3', 'blattimer2h@taobao.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Stanford', 'Patriche', 'Apt 356', 'Mundão', '120', 'spatriche2i@multiply.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Justino', 'Aysik', 'PO Box 42755', 'Ntungamo', '8553', 'jaysik2j@abc.net.au');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Elizabeth', 'Dockerty', 'Room 45', 'Cabitan', '1', 'edockerty2k@networkadvertising.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Mose', 'Mulvy', 'Room 1230', 'Täby', '827', 'mmulvy2l@vistaprint.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Gwen', 'Charlick', 'Suite 25', 'Westonaria', '9965', 'gcharlick2m@statcounter.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Adler', 'Fann', 'Apt 338', 'Khawr Fakkān', '5825', 'afann2n@e-recht24.de');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Si', 'Sellan', 'PO Box 86386', 'Blagodatnoye', '4567', 'ssellan2o@washingtonpost.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Betta', 'Wards', 'Apt 346', 'Halmstad', '902', 'bwards2p@exblog.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Elane', 'Kohen', 'Suite 97', 'Mazongshan', '0784', 'ekohen2q@google.com.hk');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Janel', 'Pawlik', 'PO Box 42171', 'Vale de Touros', '8742', 'jpawlik2r@hhs.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Sibilla', 'Cratchley', 'PO Box 79790', 'Ceper', '7622', 'scratchley0@marketwatch.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dorene', 'Heffron', 'Room 1233', 'Holýšov', '9', 'dheffron1@ezinearticles.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Gifford', 'Lampitt', 'Suite 13', 'Zavolzh’ye', '45', 'glampitt2@fastcompany.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Agna', 'Haggar', 'Suite 86', 'Reszel', '2311', 'ahaggar3@princeton.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Gerti', 'Reinert', '11th Floor', 'Sangatta', '9', 'greinert4@fastcompany.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Benni', 'Swine', 'Suite 52', 'Santarém', '0', 'bswine5@walmart.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Mathilda', 'Dessant', '5th Floor', 'Kuala Lumpur', '7', 'mdessant6@cbsnews.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Blisse', 'Dayborne', 'PO Box 64338', 'Longbo', '7', 'bdayborne7@google.co.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Netty', 'Gyse', '15th Floor', 'Puerto López', '6', 'ngyse8@ted.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Candice', 'Bynert', '19th Floor', 'Altıağac', '7416', 'cbynert9@sohu.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Farlie', 'Meadmore', 'Suite 50', 'Jinjiang', '00505', 'fmeadmorea@hatena.ne.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Nathanael', 'Ninnotti', 'Room 588', 'Kristiansand S', '02', 'nninnottib@freewebs.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Em', 'MacCumiskey', 'Room 26', 'Dan Sadau', '012', 'emaccumiskeyc@ning.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Gunther', 'MacEllen', 'Suite 88', 'Dinaig', '2', 'gmacellend@ucoz.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Talia', 'Birchill', 'Room 1894', 'East End', '13', 'tbirchille@gmpg.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Leland', 'Wedlake', 'Apt 765', 'Bangil', '6828', 'lwedlakef@nydailynews.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Chloris', 'Stiell', 'Room 528', 'Mników', '92151', 'cstiellg@elegantthemes.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Federica', 'Dalgliesh', 'Room 1548', 'Moengo', '68799', 'fdalglieshh@google.cn');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Janice', 'Giacomuzzo', 'Room 817', 'Troyes', '18', 'jgiacomuzzoi@bigcartel.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Tobin', 'Hurling', 'Suite 35', 'Warnes', '958', 'thurlingj@elegantthemes.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Carola', 'Stoyle', 'PO Box 17163', 'Bandhagen', '5857', 'cstoylek@jimdo.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Tobit', 'Bloy', 'Room 1258', 'Ararat', '52', 'tbloyl@nydailynews.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Barbara', 'Pymar', 'Suite 31', 'Winston Salem', '30', 'bpymarm@army.mil');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Pearle', 'O''Luney', 'Apt 929', 'Surkh Bilandī', '80', 'poluneyn@360.cn');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Miof mela', 'Yanshonok', 'PO Box 26417', 'Plumbon', '178', 'myanshonoko@livejournal.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Cristionna', 'Garioch', 'Apt 1308', 'Talldaww', '0', 'cgariochp@google.com.hk');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Grenville', 'Standering', 'PO Box 86321', 'Norrköping', '4', 'gstanderingq@reverbnation.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Margi', 'London', '8th Floor', 'Altuf’yevskiy', '12', 'mlondonr@sciencedaily.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ursa', 'Hamlington', 'Room 1052', 'Fushan', '9', 'uhamlingtons@elegantthemes.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Charlene', 'Adkin', 'Apt 1618', 'Verkhniy Landekh', '780', 'cadkint@seesaa.net');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Cornelius', 'Jime', 'Apt 1865', 'Ulsan', '6', 'cjimeu@skyrock.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Papageno', 'Jolly', 'PO Box 78296', 'Żelistrzewo', '1', 'pjollyv@bravesites.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Adrianna', 'Swayland', 'Room 59', 'Marau', '118', 'aswaylandw@shop-pro.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kyle', 'Woolager', 'Room 1773', 'Azun Atme', '97254', 'kwoolagerx@msu.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Anna-maria', 'Shurmer', 'PO Box 24813', 'Palcza', '761', 'ashurmery@prweb.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dasya', 'Borris', '10th Floor', 'Hezhang', '7439', 'dborrisz@wired.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Channa', 'Farry', 'Suite 77', 'Zaysan', '45335', 'cfarry10@earthlink.net');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Nola', 'Littleproud', 'PO Box 50627', 'Shuiyuan', '9', 'nlittleproud11@yelp.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ettore', 'Rodolfi', 'Suite 5', 'General Levalle', '18', 'erodolfi12@youku.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Adrianna', 'Tampling', 'Apt 1752', 'Marseille', '90031', 'atampling13@blog.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Adamo', 'Trenholm', '11th Floor', 'Nazaré', '7', 'atrenholm14@sphinn.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Yurik', 'Try', 'Apt 435', 'Vista Hermosa', '57', 'ytry15@pinterest.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Bernardine', 'Lathe', 'PO Box 30184', 'Taraban Timur', '68030', 'blathe16@studiopress.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Jayme', 'Condliffe', 'Room 1041', 'Cape Town', '73', 'jcondliffe17@foxnews.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Frederich', 'Theunissen', 'Suite 35', 'Qingkenpao', '51524', 'ftheunissen18@alibaba.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Tiffani', 'Skayman', 'PO Box 72088', 'Noisy-le-Grand', '2476', 'tskayman19@acquirethisname.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Olga', 'Rubens', 'PO Box 76421', 'Cihideung Satu', '08954', 'orubens1a@dot.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Germana', 'Heady', 'Suite 86', 'Terra Chã', '871', 'gheady1b@paypal.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Winslow', 'Cubbinelli', '6th Floor', 'Mbale', '96', 'wcubbinelli1c@ed.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Rafi', 'Dabney', '19th Floor', 'Stari Bohorodchany', '17508', 'rdabney1d@gmpg.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Wileen', 'Ebbutt', '17th Floor', 'Périgueux', '522', 'webbutt1e@elegantthemes.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Erskine', 'Hellicar', 'Suite 97', 'Mae Lan', '2683', 'ehellicar1f@europa.eu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ginnifer', 'Vernalls', '14th Floor', 'Gweedore', '45', 'gvernalls1g@ibm.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Rowen', 'Bartolozzi', 'Suite 97', 'Santa Monica', '21', 'rbartolozzi1h@topsy.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Albertine', 'Doak', '7th Floor', 'San Francisco', '631', 'adoak1i@ucla.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Myrah', 'Chardin', 'PO Box 70603', 'Kozakai-chō', '867', 'mchardin1j@thetimes.co.uk');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Shelia', 'Easby', 'Room 1639', 'Sabana Grande de Palenque', '14', 'seasby1k@sina.com.cn');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Udall', 'Rowthorn', 'Apt 926', 'Carusucan', '3503', 'urowthorn1l@nps.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Field', 'Beddoe', 'Apt 1488', 'Chengfeng', '8905', 'fbeddoe1m@soup.io');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Betsy', 'Rewbottom', 'Room 83', 'Kertosari', '9', 'brewbottom1n@nymag.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Esta', 'Heaseman', 'Apt 506', 'Västerås', '76789', 'eheaseman1o@newsvine.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Tillie', 'Bergen', 'Suite 30', 'Chengxi', '12', 'tbergen1p@unicef.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Carlee', 'Pirozzi', 'PO Box 41976', 'Dos Quebradas', '961', 'cpirozzi1q@hatena.ne.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Terencio', 'Rubenfeld', 'Suite 5', 'Yongchang', '60', 'trubenfeld1r@bravesites.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Honoria', 'Macilhench', 'Room 1632', 'Muñoz East', '4', 'hmacilhench1s@tiny.cc');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Thomasin', 'Reboul', 'Suite 34', 'Guogan', '46375', 'treboul1t@cafepress.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Rees', 'Eakeley', 'PO Box 83602', 'Moulay Abdallah', '79', 'reakeley1u@google.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Gibbie', 'Chant', 'PO Box 84047', 'Pingle', '6', 'gchant1v@tamu.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Glynda', 'Stoyle', 'PO Box 83765', 'Pegões', '0', 'gstoyle1w@redcross.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ric', 'Damper', 'PO Box 39069', 'Kapchorwa', '0336', 'rdamper1x@mapquest.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Merline', 'Dransfield', 'Apt 1760', 'Gayny', '29', 'mdransfield1y@storify.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Tamarah', 'Cliffe', 'Room 331', 'Gros Morne', '54285', 'tcliffe1z@mozilla.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Audrey', 'Danilov', 'Suite 35', 'Gunem', '9486', 'adanilov20@google.es');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Starlin', 'O''Connel', 'Apt 187', 'Tanggul Wetan', '96033', 'soconnel21@buzzfeed.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Cirillo', 'Jellico', 'Suite 86', 'Västervik', '365', 'cjellico22@buzzfeed.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Avrit', 'Pummell', '8th Floor', 'Kefar Yona', '273', 'apummell23@discuz.net');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Foster', 'Forsdyke', 'Suite 65', 'Janes', '5739', 'fforsdyke24@homestead.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Shep', 'Shark', 'PO Box 55807', 'Medellín', '3', 'sshark25@harvard.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kennie', 'Worster', 'PO Box 52136', 'Bol’shoye Selo', '3803', 'kworster26@moonfruit.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ezra', 'McAster', 'PO Box 23692', 'Mieszkowice', '43290', 'emcaster27@creativecommons.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ryley', 'Haggis', 'Apt 1721', 'Bcharré', '3709', 'rhaggis28@ihg.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Vinny', 'Chestnutt', 'Suite 47', 'Shuangyang', '4914', 'vchestnutt29@w3.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Benjie', 'Santen', 'PO Box 14622', 'Sukaraharja', '465', 'bsanten2a@twitpic.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Odey', 'Grew', 'Room 1622', 'Centenary', '62141', 'ogrew2b@myspace.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Christiano', 'Martygin', '12th Floor', 'Hamamatsu', '56', 'cmartygin2c@artisteer.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dalis', 'Fotherby', 'Suite 49', 'Dodola', '9', 'dfotherby2d@free.fr');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Jerrold', 'Smoughton', 'Apt 1231', 'Bekasi', '5', 'jsmoughton2e@reverbnation.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Tiena', 'Fridlington', 'Suite 51', 'Krajan Sumurtawang', '86', 'tfridlington2f@amazon.de');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Frayda', 'Haysham', 'Suite 38', 'Saskatoon', '04524', 'fhaysham2g@pinterest.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Eartha', 'Skingle', 'Room 1267', 'Kedungtuban', '451', 'eskingle2h@house.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dayle', 'Strutt', 'Suite 79', 'Baokou', '66', 'dstrutt2i@umich.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Win', 'MacCrachen', 'PO Box 89697', 'Lundazi', '0501', 'wmaccrachen2j@free.fr');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Rafaelia', 'Giffkins', 'Room 248', 'Saposoa', '0250', 'rgiffkins2k@twitpic.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Thadeus', 'MacCurley', 'Apt 1941', 'Philadelphia', '42', 'tmaccurley2l@topsy.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Nolie', 'Hanmer', '2nd Floor', 'Évry', '4', 'nhanmer2m@sohu.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ulrica', 'Blanden', 'Room 1235', 'Zhicheng', '84', 'ublanden2n@t.co');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Hermione', 'Masdon', '8th Floor', 'Salerno', '3331', 'hmasdon2o@networksolutions.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Nessa', 'Kembery', 'Apt 34', 'Qiwen', '0', 'nkembery2p@forbes.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Cirilo', 'McOwan', '4th Floor', 'Shamkhor', '4393', 'cmcowan2q@nhs.uk');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kenna', 'Towns', '18th Floor', 'Berestechko', '635', 'ktowns2r@storify.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kendre', 'Ohms', 'Apt 1422', 'Zbýšov', '04241', 'kohms2s@mapy.cz');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Bertrand', 'O''Haire', 'Suite 74', 'Potrero Grande', '735', 'bohaire2t@wikispaces.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Enrico', 'Stabler', 'Apt 753', 'Ukata', '21', 'establer2u@epa.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Jean', 'De Carteret', 'Suite 92', 'Mkiriwadjumoi', '986', 'jdecarteret2v@sourceforge.net');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Carlin', 'Claughton', '15th Floor', 'Chandler', '8', 'cclaughton2w@alexa.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Allys', 'Schurcke', 'Apt 1741', 'Gonghe', '34801', 'aschurcke2x@github.io');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Taddeusz', 'McArthur', 'Suite 33', 'Meaux', '4997', 'tmcarthur2y@1und1.de');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Evaleen', 'Goodwin', 'Room 989', 'Obninsk', '402', 'egoodwin2z@spotify.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Quentin', 'Serraillier', 'PO Box 28317', 'Czyżowice', '684', 'qserraillier30@nba.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Vance', 'Batchelor', 'Room 1614', 'Ad Dujayl', '49', 'vbatchelor31@issuu.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Flora', 'Shimmin', 'Apt 1949', 'Guachucal', '9800', 'fshimmin32@irs.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Elinor', 'Newbegin', 'PO Box 92145', 'Lingda', '110', 'enewbegin33@oracle.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Car', 'Finkle', '12th Floor', 'Pangao', '91', 'cfinkle34@livejournal.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Micheline', 'Cottill', 'PO Box 35637', 'Bojano', '54', 'mcottill35@narod.ru');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Revkah', 'Thoresby', 'PO Box 43222', 'Herálec', '9', 'rthoresby36@tuttocitta.it');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Malinda', 'Veneur', 'Suite 32', 'Ngurenrejo', '2515', 'mveneur37@house.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Danica', 'Kilgallon', '15th Floor', 'Dongshan', '70169', 'dkilgallon38@stumbleupon.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Felix', 'Biggen', '2nd Floor', 'Fukou', '56505', 'fbiggen39@theglobeandmail.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Joy', 'Smails', 'Apt 608', 'Huohua', '61954', 'jsmails3a@washington.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Olin', 'Bebbell', 'Apt 1594', 'Cafarnaum', '29', 'obebbell3b@dailymotion.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Roxane', 'Hidderley', 'PO Box 32716', 'Krajan', '833', 'rhidderley3c@chronoengine.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Akim', 'Leipold', 'Room 1237', 'Bebekan', '8330', 'aleipold3d@seattletimes.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Thomas', 'McIlwrath', '14th Floor', 'Lena', '889', 'tmcilwrath3e@oracle.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ronni', 'Saura', '3rd Floor', 'Dao', '67265', 'rsaura3f@eventbrite.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dina', 'Domenge', '19th Floor', 'Lazarevskoye', '161', 'ddomenge3g@google.com.br');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Thomasin', 'Grigorey', 'Suite 73', 'Furong', '4624', 'tgrigorey3h@globo.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Marcellina', 'Atley', '12th Floor', 'Lintaca', '6', 'matley3i@live.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Shepherd', 'Middle', 'Apt 248', 'Torino', '237', 'smiddle3j@chicagotribune.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Mercy', 'Rattenbury', 'Room 319', 'Lũng Hồ', '61', 'mrattenbury3k@infoseek.co.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dorotea', 'Kardos-Stowe', 'Suite 34', 'Yermolino', '2710', 'dkardosstowe3l@t.co');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Donal', 'Eykelhof', 'Room 53', 'Irecê', '94', 'deykelhof3m@sfgate.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Lauren', 'Dawby', 'PO Box 62117', 'Bayan Uula Sumu', '17', 'ldawby3n@prlog.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ursuline', 'Laird', 'PO Box 33375', 'Birobidzhan', '2', 'ulaird3o@ebay.co.uk');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Davine', 'McLeish', 'PO Box 80853', 'Kaulon', '1', 'dmcleish3p@zdnet.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Willie', 'Alps', 'PO Box 57894', 'Odivelas', '213', 'walps3q@google.com.au');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Karita', 'Barents', 'PO Box 64193', 'Lyon', '0', 'kbarents3r@mozilla.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Sloan', 'Sturm', 'PO Box 36866', 'Burao', '0003', 'ssturm3s@vk.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Fonz', 'Peizer', 'PO Box 84165', 'Lewolere', '7351', 'fpeizer3t@discovery.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Tommy', 'Hardaway', 'Suite 19', 'Sernovodsk', '1', 'thardaway3u@addtoany.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Shay', 'Hulke', 'Room 1973', 'Honiara', '27701', 'shulke3v@samsung.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Eula', 'Hancell', 'Suite 10', 'Zhanghua', '427', 'ehancell3w@opensource.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Katherine', 'Cissell', 'Apt 1769', 'Shiban', '399', 'kcissell3x@is.gd');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Viki', 'Heaford', 'Room 303', 'Lakkíon', '92', 'vheaford3y@google.it');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kimball', 'Guerrier', 'PO Box 72673', 'Taltal', '01573', 'kguerrier3z@sourceforge.net');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Chan', 'Feechum', 'Room 930', 'Drammen', '41', 'cfeechum40@home.pl');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Coralie', 'Critch', 'Room 246', 'Changfu', '7952', 'ccritch41@stanford.edu');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Koralle', 'Weerdenburg', 'Suite 59', 'Kōriyama', '368', 'kweerdenburg42@xing.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Alanson', 'Baxstare', '9th Floor', 'Rudnogorsk', '37879', 'abaxstare43@geocities.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Darryl', 'Sympson', 'PO Box 45495', 'Cambanugoy', '453', 'dsympson44@constantcontact.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Lilllie', 'Dykas', 'Apt 912', 'Wilmington', '11345', 'ldykas45@list-manage.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Jimmie', 'Chatters', 'Apt 843', 'Caringin', '7', 'jchatters46@booking.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Clerc', 'Kitchin', 'Suite 91', 'Santander', '1', 'ckitchin47@hp.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kristos', 'Loffhead', '15th Floor', 'Ojiya', '1', 'kloffhead48@last.fm');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Sarah', 'Fenty', 'Suite 81', 'Sezemice', '69', 'sfenty49@oakley.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Maryjane', 'Yurinov', '1st Floor', 'Aldeia da Bela Vista', '94725', 'myurinov4a@skype.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Adlai', 'Scholefield', '17th Floor', 'Xieyang', '820', 'ascholefield4b@xing.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Eldin', 'Fortin', '15th Floor', 'Bejsce', '10291', 'efortin4c@deviantart.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ann', 'Breissan', 'Suite 90', 'Catujal', '96', 'abreissan4d@nationalgeographic.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Branden', 'Tiffney', '15th Floor', 'Le Grand-Quevilly', '20900', 'btiffney4e@answers.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Fanni', 'Ure', 'Apt 198', 'Marovoay', '4', 'fure4f@hatena.ne.jp');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ardisj', 'McKellar', 'Apt 1874', 'Gengqing', '39', 'amckellar4g@fastcompany.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Matty', 'Ciardo', 'PO Box 50150', 'Paipa', '1869', 'mciardo4h@craigslist.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Curr', 'Wakeley', 'PO Box 65300', 'Mitaka-shi', '13', 'cwakeley4i@about.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Bernie', 'Asson', 'Suite 13', 'Maumere', '685', 'basson4j@geocities.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Adah', 'Keenleyside', 'Suite 44', 'Zhongfan', '20637', 'akeenleyside4k@taobao.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Gretchen', 'Arndt', 'PO Box 8577', 'Phultala', '878', 'garndt4l@prweb.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Louie', 'Sharrocks', '3rd Floor', 'Haljala', '271', 'lsharrocks4m@google.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Theressa', 'Grooby', 'Apt 60', 'Lecherías', '5606', 'tgrooby4n@hp.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Yvon', 'O''Ferris', 'Apt 1398', 'Śniadowo', '12', 'yoferris4o@bbc.co.uk');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Andras', 'Roscamps', 'Suite 67', 'Göteborg', '0508', 'aroscamps4p@xinhuanet.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Flint', 'Hayworth', 'Suite 85', 'Meylan', '06', 'fhayworth4q@unesco.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Joanne', 'Sacaze', 'Room 272', 'Ciénaga de Oro', '5', 'jsacaze4r@mtv.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Marja', 'Aymeric', 'Apt 1284', 'Åmål', '21875', 'maymeric4s@un.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Sauncho', 'Antowski', '2nd Floor', 'Souto da Costa', '5', 'santowski4t@dot.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Nannette', 'Stable', 'PO Box 87808', 'Gutian', '445', 'nstable4u@techcrunch.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Layla', 'McCurley', '8th Floor', 'Takasaki', '4397', 'lmccurley4v@desdev.cn');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Tomi', 'Joesbury', 'Apt 673', 'Hamilton', '4321', 'tjoesbury4w@tripadvisor.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Fallon', 'Kayley', 'Suite 100', 'Donghoufang', '66', 'fkayley4x@diigo.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Weidar', 'Clericoates', 'Suite 32', 'Kyaikto', '01', 'wclericoates4y@google.es');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Deanna', 'Abade', 'Room 1136', 'Luleå', '5189', 'dabade4z@foxnews.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dorelia', 'A''field', 'PO Box 26179', 'Qulaybīyah', '58', 'dafield50@imgur.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ethelyn', 'Ragles', 'Suite 63', 'El Tablón', '199', 'eragles51@yelp.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dawna', 'Mahoney', 'Room 1119', 'Santa Cruz do Bispo', '627', 'dmahoney52@fotki.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Gnni', 'Wallbrook', 'PO Box 66375', 'Kelīshād va Sūdarjān', '4236', 'gwallbrook53@ask.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Duky', 'McAllen', '8th Floor', 'Kesha', '1', 'dmcallen54@spotify.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Joana', 'Shepard', 'PO Box 56623', 'Vidyayevo', '70796', 'jshepard55@dedecms.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Ramonda', 'Wastling', 'Room 1265', 'Huanglong', '3446', 'rwastling56@amazon.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Rochester', 'Hanselman', '2nd Floor', 'Birao', '3166', 'rhanselman57@google.ru');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Dorella', 'Benzing', '16th Floor', 'Charlottesville', '613', 'dbenzing58@google.fr');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Marilee', 'Bowyer', 'Suite 28', 'Santa Rita', '925', 'mbowyer59@sfgate.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Milli', 'Lernihan', '8th Floor', 'Majunying', '328', 'mlernihan5a@hubpages.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Inga', 'Allnutt', 'PO Box 21038', 'Qila Saifullāh', '39', 'iallnutt5b@cocolog-nifty.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Annabell', 'Mushett', 'PO Box 4715', 'Sorocaba', '38380', 'amushett5c@bizjournals.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Theodosia', 'Stavers', 'Apt 34', 'Borås', '2345', 'tstavers5d@networkadvertising.org');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Otho', 'Bunnell', 'Room 587', 'Ndungu', '53606', 'obunnell5e@gizmodo.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Griswold', 'Stanett', '17th Floor', 'Shulan', '764', 'gstanett5f@nsw.gov.au');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Marabel', 'Sprakes', 'PO Box 93698', 'Syamzha', '441', 'msprakes5g@java.com');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Alistair', 'Mandeville', 'Suite 34', 'Trstenik', '43369', 'amandeville5h@mail.ru');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Betteanne', 'Scutchings', 'Apt 1344', 'Ban Phan Don', '49', 'bscutchings5i@hud.gov');
insert into customer (firstName, lastName, address, city, zipcode, email) values ('Kayne', 'Enga', 'Apt 157', 'Lyntupy', '4', 'kenga5j@army.mil');
